### PR TITLE
avoid Mutex module name clash

### PR DESCRIPTION
**Pull request by agarwal**
The `Mutex` module name causes problems since it exists in the OCaml threads library. I renamed it to `Redis_mutex`.

### CODE REVIEW

**Comment by rgrinberg** [comment]
How can it cause problems if the Mutex inside a pack?

**Comment by agarwal** [comment]
Hmm... I can't reproduce either of the problems I had just a few hours ago. One was a warning about mutex.cmi existing in multiple directories. I think that happens due to the way ocamlfind works, not ocaml per se. The second was an error about inconsistent assumptions over interface mutex.cmi when loading redis in utop.

You may well be right that there shouldn't be a problem when you pack modules, but I've never quite managed to figure out what exactly can be done to avoid warnings at the least.

**Comment by agarwal** [comment]
Finally, in some sequence of events, I got my two errors again:

> # findlib: [WARNING] Interface mutex.cmi occurs in several directories: /home/aa1/.opam/4.02.3/lib/redis, /home/aa1/.opam/4.02.3/lib/ocaml/threads

This is no different than the warning about [topdirs.cmi](http://caml.inria.fr/mantis/view.php?id=6754) that has been open for a long time. So on the one hand, we could say this is not a fault of ocaml-redis. As a practical matter however, this warning is avoided by this pull request.

> # Error: The files /home/aa1/.opam/4.02.3/lib/core/core.cmi
> #        and /home/aa1/.opam/4.02.3/lib/redis/mutex.cmi
> #        make inconsistent assumptions over interface Mutex
> # Command exited with code 2.

I'm not sure why I get this sometimes and not other times (I've always been using ocaml-redis in the presence of Core). Is it simply that mutex.cmi should not be installed?

**Comment by hcarty** [comment]
Would it be enough to move `Mutex` to `InternalModules`?

**Comment by let-def** [comment]
Why installing `mutex.cmi` if it is packed? Interfaces of modules that got packed shouldn't be installed.

**Comment by agarwal** [comment]
@let-def Not installing `mutex.cmi` would resolve the problem for users of this library. However, isn't it still a problem during build? Prior to packing, you do have to compile `mutex.mli` and at that point you'll get a name clash.

**Comment by let-def** [comment]
I didn't look in detail, but it seem only the examples are built with threads flag.
The module pack cannot see the thread modules, so no Mutex conflict.

**Comment by rgrinberg** [comment]
My port to jbuilder #46 fixes this issue.

**Comment by rgrinberg** [comment]
@aluuu this can be closed now

**Pull request closed without merging**
