### PR TITLE
add unix to redis_lwt build depenencies in _oasis.

### PR DESCRIPTION
**Pull request by phaer**
Without adding it, I am getting the following error:

`+ ocamlfind ocamlopt -linkpkg -package redis.lwt -package lwt.unix -package unix -package lwt.ppx -package websocket.lwt -package yojson broker.cmx -o broker.native
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Unix referenced from /home/phaer/.opam/4.02.3/lib/redis/redis.cmxa(Redis)
Command exited with code 2.
Compilation unsuccessful after building 4 targets (0 cached) in 00:00:00.
`

### CODE REVIEW

**Comment by aluuu** [comment]
Hello, @phaer.

I've tried, but I can't reproduce your problem. 
Could you, please, provide [minimal working example](https://stackoverflow.com/help/mcve)?

**Comment by let-def** [comment]
I confirm that `unix` dependency is missing.

`src/mutex.ml` depends on `Unix` (`Unix.time()` line 10), but the dependency does not appear in META.
The build is underspecified, and success depends on other dependencies (some dep might specify Unix) and the order of argument (final ocamlopt invocation must specify unix.cm(x)a before redis).

**Comment by let-def** [comment]
(But the fix should add Unix to Redis BuildDepends, not Redis_lwt)

**Comment by Leonidas-from-XIV** [comment]
`ocaml-redis` does not use `oasis` anymore, so this PR can be closed I think.

**Pull request closed without merging**
