### PR TITLE
Pass hints to getaddrinfo

### PR DESCRIPTION
**Pull request by sepeth**
When getaddrinfo returns an IPv6 address info, ocaml-redis gives the following error:

```
Uncaught exception:
  
  (Unix.Unix_error "Address family not supported by protocol family" connect
   "")

Raised by primitive operation at file "src_sync/redis_sync.ml", line 31, characters 4-29
```

On my OS, for "localhost" query, getaddrinfo returns both IPv4 and IPv6 addresses. But ocaml-redis chooses the first one. If the chosen one is IPv6 address, I get the error above, because ai_family parameter to Unix.socket was hardcoded (PF_INET, but it should be PF_INET6 when the address is IPv6). So I checked the official C redis client to see how it deals with this situation, and implemented the same idea for ocaml-redis. I think, the comments in the following link has some valuable information, and if you agree with it, I can add the same comment to this PR:

https://github.com/redis/hiredis/blob/64d1ec8342e50354e6e3c5757bb99d4652dd9f3c/net.c#L325

### CODE REVIEW

**Comment by sepeth** [comment]
Hmm, I've used `let%lwt`, and I guess ppx is not available on 4.01. One check have failed and it printed:

```
ocamlfind: Package `lwt.ppx' not found
```

Should I write that part without ppx? `let%lwt` makes it a bit easier to read though.

**Comment by aluuu** [comment]
Hello @sepeth,

Thanks for contribution, very useful changes, IMO.

I think that package should work at least with last 3 major releases of compiler. As I see, extension nodes (ppx) were intorduced in OCaml 4.02.  It would be great if you'll edit your PR to avoid usage of `lwt.ppx`.

I'll merge the PR as soon as you fix it.

**Comment by sepeth** [comment]
Thanks, I am still new in OCaml world ^_^

I think I got it right this time, let's see how travis builds will go ^_^

**Comment by aluuu** [comment]
Great! Thanks for fixes.

**Pull request merged**
