### PR TITLE
Enable safe-string support

### PR DESCRIPTION
**Pull request by jpdeplaix**
The interface needed a bit of change to be compilable using OCaml 4.06.0 or any other compiler versions with safe-string enabled.
Let me know if the changes are ok or not.

### CODE REVIEW

**Comment by jpdeplaix** [comment]
Ping @0xffea @aluuu @khady (I don't know who has commit rights)

**Comment by 0xffea** [comment]
@jpdeplaix Thanks for your contribution.

**Comment by jpdeplaix** [comment]
Thanks. Any plans to make a release soon by any chance ?

**Comment by 0xffea** [comment]
I don't think so, sorry. There is just your change since the last release.

**Comment by jpdeplaix** [comment]
Ok, but precisely it can be a good target for a minor release to be able to compile it with OCaml 4.06 and up, I believe.

**Comment by jpdeplaix** [comment]
What do you think ? Otherwise I just might just use the patch in the opam package but I believe it's much cleaner if it's done via a proper release.

**Comment by rgrinberg** [comment]
@0xffea if you don't have the bandwidth to make releases please consider someone else helping you with that. Make emergency bug fixes like this available promptly is quite important for the community. We definitely understand if you're too busy for this stuff at the moment.

**Comment by 0xffea** [comment]
@rgrinberg I thought this is just a default switch in ocaml 4.06.

**Comment by rgrinberg** [comment]
@0xffea it is. but this new default makes some old code (which doesn't respect the bytes vs. string distinction) to fail to compile.

**Comment by jpdeplaix** [comment]
Please @0xffea, if you have some spare time, please consider doing this. 
It shouldn't take too long and also makes users happy :)

**Comment by kit-ty-kate** [comment]
PLEAAASE. It's *really* a blocker for me and I don't really want to patch the current version in opam as the interface has changed slightly.
Again, please consider doing this and call for help if you don't have enough time.

**Comment by 0xffea** [comment]
I released a new version, but it seems there are build errors in travis. Someone should test it before adding it to opam.

**Comment by kit-ty-kate** [comment]
Thanks a lot !! I'll add that to opam-repository right away ! :)
The travis failures look unrelated.

**Pull request merged**
