### PR TITLE
String.create -> Bytes.create to silence warning on recent OCaml vers…

### PR DESCRIPTION
**Pull request by hcarty**
…ions

This adds a dependency on the compatibility "bytes" package for earlier
versions of OCaml

### CODE REVIEW

**Comment by hcarty** [comment]
Force-pushed an update to opam as well to reflect the `bytes` dependency

**Comment by hcarty** [comment]
I'm not sure what the OCaml 4.03.0 failure is - seems to be unrelated to this PR?

**Comment by 0xffea** [comment]
Thanks for the patches Hezekiah. I will try look at the 4.03 failure, but I have an upcoming paper deadline. So it will need some time.

**Comment by aluuu** [comment]
Hello, @hcarty.

Could you rebase your changes on top of current master? Several changes which fix CI failure has been commited. I could merge your pull request after the rebase.

Thanks.

**Comment by hcarty** [comment]
Yes, I can do that - or, possibly just redo the change since it's pretty simple anyway.  I'll try to get this early next week.

**Comment by aluuu** [comment]
Ok, thanks. I've created duplicate of this PR with proper commit history. I'll close this PR and merge the new one.

**Pull request closed without merging**
