### PR TITLE
try to fix CI

### PR DESCRIPTION
**Pull request by Et7f3**
Ignore me I try to see if it is specific to windows.

### CODE REVIEW

**Comment by Et7f3** [comment]
Why ???? why did you merge this draft and why it is green (on my account it is red)

**Comment by c-cube** [comment]
No worries, I just had to restart the tests, it was a timing error. I can fix the trigger on master.

**Comment by c-cube** [comment]
although, ok, I hadn't seen it was on another PR?

**Comment by Et7f3** [comment]
It is on that branch, that's why I added wip-ocaml in push trigger. Will try to look again tomorrow seem the tests are fixed.

**Pull request merged**
