### PR TITLE
Async support

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
We want to use ocaml-redis in an Async application, so here's a backend for Async. It was quite doable since the library already has a Lwt and sync backend. The main issue was creating a recursive lock to implement `atomic` but I believe it could be solved in a different way. Anyway, changing this is out of scope for now.

I found a bug in the library as well, since the `IO.iter` should be `IO.iter_serial` in any case, because writing out the command arguments depends on the order.

Also, I have made the `ECHO` test a bit more robust. These fixups in separate commits, if you feel like cherry-picking parts.

### CODE REVIEW

**Comment by 0xffea** [comment]
A CI download is broken. http://download.camlcity.org/download/findlib-1.7.3.tar.gz

**Comment by Leonidas-from-XIV** [comment]
"Fixed" this by re-pushing the same commit. Now it fails because Travis is broken and the runtest requires both `redis-lwt` and `redis-async` packages. I guess it would be best if each had their own `runtest`, need to look into this.

**Comment by c-cube** [comment]
Would this still be of interest to you, @Leonidas-from-XIV ?

**Comment by Leonidas-from-XIV** [comment]
@c-cube No, I was thinking on how to tackle this but ocaml-redis' Lwt binding depends on `Lwt.atomic` to sync up the reading and writing which is hard to do in Async, so I [wrote my own bindings](https://github.com/Leonidas-from-XIV/orewa/) that are designed from the ground to be non-blocking (currently they don't support Lwt though).

**Pull request closed without merging**
