### PR TITLE
a few improvements to the sorted set operations

### PR DESCRIPTION
**Pull request by domsj**

### CODE REVIEW

**Comment by aluuu** [comment]
Hello @domsj ,

Could you add some tests for the functions you implemented? 
If have no time for it, I'll do it for you this weekend and then I'll merge this PR.

**Comment by domsj** [comment]
I'll try to see if I can find the time (before the weekend as then I'm leaving on holiday), but can't guarantee...
I'm guessing there were no tests yet for anything sorted set related as I changed a few signatures and there were no compile errors in any tests?

Btw for the zadd function ( http://redis.io/commands/zadd ) I'm considering adding support for the NX/XX flags, which are only available for redis >= 3.0.2, would you be interested in that too?

Any plans for a new release sometime after those changes?

**Comment by aluuu** [comment]
Yes, not all code base is covered with test, so I think it's good practice to write tests at the same time with introduction of new functionality.

I'm absolutely interested in support of NX/XX flags. It would be great if the library would support latest features of redis.

Sure. It would be major release (0.3.0), because module signatures changed a lot since last released version. 
I wanted to finish all the commands implementations before new release but I'm not sure that I could do it in the nearest future. So, I think that I could release new version right after merging this PR.

**Comment by domsj** [comment]
Hi @aluuu,

Please check my new commits. I've added more options for the zadd function, and wrote a test.
I also tried to make the travis build fail whenever a test fails, but did not yet succeed. I think it now requires some fiddling with the oasis build stuff, which I'ld rather not touch :-).

A new release would be great, thanks already!

**Comment by aluuu** [comment]
Thanks for contribution. I've found what's wrong with test running in sense of exit code and I'll fix it right after the merge.

**Comment by aluuu** [comment]
Hi, @domsj 

My PR that releases redis-0.3.0 [was merged](https://github.com/ocaml/opam-repository/pull/6932) into OPAM repository. So, you can `opam update` and install redis-0.3.0.

**Pull request merged**
